# Generated by Django 5.2.1 on 2025-05-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("shipped", "Shipped"),
                            ("canceled", "Caneled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
